        <meta charset="UTF-8">
        <title>Title</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Curriculum Vitae - Développeur web Junior - Zanetti Jordan">
        <meta name="keywords" content="Développeur web, Curriculum Vitae, HTML5, CSS3, Sass, JavaScript, WordPress, Prestashop, Photoshop, Adobe XD, Développeur Front-End, Intégration web, ">
        <meta name="author" content="Zanetti Jordan">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">
        <link rel="stylesheet" type="text/css" href="/styles/bsmain.css">